elodin-sys/elodin

- README.md
The presence of a `'` was causing issues when copy and pasting the code into someone's terminal. Removed it
fixes https://github.com/elodin-sys/elodin/issues/6
> fix: remove single quote in readme

- libs/nox/src/tensor.rs
Following the discussion in [issue11](https://github.com/elodin-sys/elodin/issues/11), here is a PR adding doc comments to `tensor.rs`. This is a first test in introducing AI-generated comments to document the library faster, making it easier to pick up by new users.
Here is a preview of what it looks like in conditions (`cargo doc --open --no-deps --all-features`):
This is a test to think about the viability of this approach. Do feel free to comment and criticize (things can definitely be streamlined by hand, this PR had no manual tweak of the comments so far)!
For archival purposes, here is the prompt used to generate the comments (with GPT-4):
```
You will be given code from `nox`, a Rust implementation of JAX. Your goal is to doc-comment the code:
* adding a top-level doc comment …
```
> Added doc-comments to tensor.rs

- libs/nox/src/builder.rs
- libs/nox/src/client.rs
- libs/nox/src/comp.rs
- libs/nox/src/comp_fn.rs
- libs/nox/src/constant.rs
- libs/nox/src/error.rs
- libs/nox/src/exec.rs
- libs/nox/src/fields.rs
- libs/nox/src/jax.rs
- libs/nox/src/local_backend.rs
- libs/nox/src/matrix.rs
- libs/nox/src/noxpr.rs
- libs/nox/src/param.rs
- libs/nox/src/quaternion.rs
- libs/nox/src/scalar.rs
- libs/nox/src/spatial.rs
- libs/nox/src/tensor.rs
- libs/nox/src/transfer.rs
- libs/nox/src/vector.rs
Following the discussion in [issue 11](https://github.com/elodin-sys/elodin/issues/11) and the preliminary test in [PR 12](https://github.com/elodin-sys/elodin/pull/12), here is a PR adding doc comments to the entire Nox codebase. As previously stated, the comments are AI-generated, with the goal of speeding up the documentation of the library (it is easier to improve a bad comment than to write one from scratch).
The PR is best examined by generating the documentation (`cargo doc --open --no-deps --all-features`).
Do not hesitate to comment and criticize; some comments will definitely require manual improvements.
One thing that is still missing, and should probably be done by hand, is a `lib.rs` top comment that serves as a documentation readme (ideally with a small code …
> Added doc-comments to Nox

- README.md
Recommend installing the pre-built wheels from PyPi. Also, use one of the in-repo examples as it'll be maintained. The README was consistently out of date, and having multiple different documentation sources is a maintenance burden.
> Simplify the getting started process

- .buildkite/pipeline.py
- docs/public/content/home/aleph/setup.md
- images/aleph/README.md
- images/aleph/deploy.sh
- images/aleph/modules/elodin-db.nix
[support remote offline builds](https://github.com/elodin-sys/elodin/pull/25/commits/db5c1aa8c26e6f88487e0dc6b1a9a16b97468eba)
One annoying issue that people could run into when setting up Aleph is:
remote builds on Aleph currently require access to substituters. So, if
Aleph is offline, the remote builds will fail.
It's easy enough to connect Aleph to WiFi now, but that's only in the
recent OS images. People still have to upgrade their old OS images
somehow.
This change attempts to do remote builds while preventing the builder
(Aleph) from using its susbstituters. The host machine can still
download dependencies and final artifacts from binary caches and copy
them onto Aleph. Unfortunately, nix remote builds are still pretty buggy
and I still see occasional random lockups or cases when …
> Better support for remote + offline builds, deploy.sh args

- libs/stellarator/maitake/src/scheduler.rs
- libs/stellarator/src/lib.rs
- libs/stellarator/src/poll/mod.rs
- libs/stellarator/src/uring/mod.rs
This PR fixes a series of issues that occurred when an executor was dropped. There were two primary problems: 
- `finalize_io` was initially designed to prevent the problem of inflight io_uring operations causing memory corruption. Imagine if you had a waiting `Read` op, and the buffer gets de-allocated, the kernel could clobber some random buffer. So `finalize_io` waited for all the inflight IO to complete. The problem is that some inflight io might never complete, like a `read` or `accept` which could leave a thread hanging. Now we explicitly issue `AsyncCancel` request so the kernel won't write into a de-alloced buffer.
- Previously we were de-allocating the reactor by simply taking the Executor, and dropping it. This caused issues because  when dropping tasks they would attempt to …
> fix(stellar): fix nested reactor access in cleanup

- Cargo.lock
- apps/inscriber/Cargo.toml
- apps/inscriber/src/main.rs
- images/aleph/deploy.sh
- images/aleph/modules/hardware.nix
This PR enables compression for sd-images to make easier to distribute. It also adds auto-decompression support to inscriber to make flashing these images easy. 
https://github.com/user-attachments/assets/c2d0fcaa-0963-4212-9e79-b82823548043
> Compress aleph-os sd-image and add zstd support to inscriber

- images/aleph/flake.nix
The previous key pair would get rotated on every restart of the CI VM. The new key pair is saved in 1p and injected via opnix.
> Replace ephemeral trusted key with one persisted in 1p

- docs/public/content/home/aleph/fc_board_flash.md
- fsw/sensor-fw/README.md
0.27 fixed the STM32H7 memory map. Also, the official install instructions are fine + more likely to work.
> docs: Don't recommend older probe-rs version

- docs/public/content/home/aleph/setup.md
- images/aleph/README.md
- images/aleph/deploy.sh
- images/aleph/modules/aleph-dev.nix
- images/aleph/modules/usb-eth.nix
- images/aleph/modules/wifi.nix
- images/aleph/template/flake.nix
Also, use fde1:2240:a1ef::1 instead of aleph.local. mDNS seems even more unreliable for the IPv6 ethernet gadget connection. Tried on 2 Linux systems and it didn't work OOTB. It's also very flaky on macOS. I think the more standard network interfaces (wifi, ethernet) are a bit more reliable with hostname resolution because they advertise their hostnames when requesting an IP over DHCP and the router is advertising the hostname. So, you can rely on router to help out in case mDNS isn't working.
> feat(os): use hardware serial-number to generate hostname

- fsw/aleph-setup/src/main.rs
- images/aleph/modules/aleph-dev.nix
- images/aleph/scripts/cudainfo.py
- Add user to video group to use cuda without sudo.
- Enable `hardware.graphics` to symlink `libcuda.so` to `/run/opengl-driver/lib/`. All nix packages that depend on cuda are patched with an rpath that includes this directory. With this change, setting LD_LIBRARY_PATH is no longer required for native nix packages. It's still needed for python scripts unfortunately.
- Add nvcc, pycuda. nvcc only works with gcc <= 11. Also, it needs to be informed of the header file location. So, I'm setting `NVCC_PREPEND_FLAGS` and `NVCC_APPEND_FLAGS` to address this. I'm not sure if there's a better way.
> Add pycuda, fix libcuda.so not found issue

- .buildkite/pipeline.py
We can make this more convenient but with this change, you'll be able to go to the latest main build on buildkite and download the sdimage directly.
> chore: upload sd image to gcs on main builds

- apps/elodin/README.md
- apps/elodin/install-editor.sh
- libs/db/README.md
```
curl -LsSf https://storage.googleapis.com/elodin-releases/install-editor.sh | sh
```
Doesn't work Windows, but I still find it useful.
> chore: add an install script for the editor

- CHANGELOG.md
- Cargo.lock
- libs/elodin-editor/Cargo.toml
- libs/elodin-editor/src/lib.rs
- libs/elodin-editor/src/offset_parse.rs
- libs/elodin-editor/src/plugins/navigation_gizmo.rs
- libs/elodin-editor/src/ui/preset.rs
- libs/elodin-editor/src/ui/tiles.rs
- libs/elodin-editor/src/ui/utils.rs
- libs/elodin-editor/src/ui/widgets/command_palette/mod.rs
- libs/elodin-editor/src/ui/widgets/command_palette/palette_items.rs
- libs/elodin-editor/src/ui/widgets/inspector/entity.rs
- libs/elodin-editor/src/ui/widgets/inspector/graph.rs
- libs/elodin-editor/src/ui/widgets/inspector/mod.rs
- libs/elodin-editor/src/ui/widgets/label.rs
- libs/elodin-editor/src/ui/widgets/plot/bars.wgsl
- libs/elodin-editor/src/ui/widgets/plot/data.rs
- libs/elodin-editor/src/ui/widgets/plot/gpu.rs
- libs/elodin-editor/src/ui/widgets/plot/points.wgsl
- libs/elodin-editor/src/ui/widgets/plot/state.rs
- libs/elodin-editor/src/ui/widgets/plot/widget.rs
- libs/elodin-editor/src/ui/widgets/timeline/timeline_controls.rs
- libs/impeller2/src/types.rs
- libs/impeller2/wkt/src/gui/mod.rs
- libs/nox-py/src/well_known/gui.rs
**Add Point + Bar Plotting**
I added two new line types to the editor, point, and bar. This is done by adding two new shaders, and then using shader specialization to determine which to use at runtime
**Fix tab switching shortcut**
Previously if you used ctrl-tab it would move too fast to be useful. It now uses just_pressed so the user can move a single tab at a time
**Add right click menu to set current graph range as editor time range**
https://github.com/user-attachments/assets/866a4e61-4b6a-4b95-8059-e80ae39ffa51
**Add a command palette action to set the time range to a custom region**
https://github.com/user-attachments/assets/ae49d611-626e-4676-8b9e-f372bc4761f8
**Allow renaming graph panels**
https://github.com/user-attachments/assets/cd439dd9-d363-4e96-bda2-6373b1cb9f08
> Add a bunch of small missing features to the editor

- Cargo.lock
- libs/db/Cargo.toml
- libs/db/src/arrow.rs
- libs/db/src/lib.rs
- libs/db/src/time_series.rs
This PR adds a new new streaming tables to the datafusion session. They allow you to query streaming data as it comes in. I had hoped this would be more useful than it is, and would allow you to do stuff like streaming the average of data. But it seems pretty limited right now. Never the less, this should set us up well for when data fusion adds more features
> feat(db): add sql stream tables

- fsw/c-blinky/.gitignore
- fsw/c-blinky/README.md
- fsw/c-blinky/build.sh
- fsw/c-blinky/linker.ld
- fsw/c-blinky/main.c
This is a minimal, fully understandable reference for board power and clock setup. It's ~240 lines in a single C file with zero dependencies - just direct register manipulation that anyone can read and debug. When hardware issues come up, having a baseline that definitely works helps isolate problems quickly. It also includes a full RTT target implementation.
> Add a C blinky

- fsw/openocd/flash.sh
- fsw/sensor-fw/src/fm24cl16b.rs
- fsw/sensor-fw/src/i2c_dma.rs
- fsw/sensor-fw/src/lib.rs
- fsw/sensor-fw/src/main.rs
- fsw/sensor-fw/src/usb2513b.rs
This is needed for the USB hub to function. In the next revision, instead of writing directly to the hub, this'll probably write to an i2c eeprom instead. Turns out there's a lot of annoying stuff to configure on a hub for it to work well in all scenarios and strapping resistors aren't robust enough.
> feat(fw): initialize USB hub over smbus

- fsw/sensor-fw/src/main.rs
This is just handy to have setup in case we need to do print debug stuff and don't have RTT access. It's also useful for testing the debugprobe firmware + pinout.
> feat(fw): write to uart6 to test debugprobe

- images/aleph/modules/usb-eth.nix
This PR pins the device-side and host-side mac address of the aleph to a valid [unicast mac address](https://en.wikipedia.org/wiki/MAC_address#Ranges_of_group_and_locally_administered_addresses).
The previous value was not a valid individual mac address and the setting was being ignored by the kernel driver. With the previous setting, the configuration on aleph-os would result in a random device-side & host-side mac address being set upon each boot. From a developer-perspective, this resulted in a new NIC device appearing upon each reboot of aleph-os. If you had a device-specific network setting applied (with eg. NetworkManager), then those settings would not be applied on aleph reboots, since a new, unique device would appear after each reboot.
This fix gives aleph-os a static mac …
> fix(aleph-os): usb gadget mac address to unicast

- .github/workflows/deploy-docs.yml
- docs/public/DEPLOYMENT.md
- docs/public/README.md
Moving Docs site generation & hosting to Github Actions/Pages, including preview sites for PRs.
> Add GitHub Pages deployment with PR previews

- libs/nox-py/python/elodin/__init__.py
- libs/nox-py/python/elodin/jaxsim.py
When implementing Software In The Loop (SITL) testing using Elodin's JaxSim interface, the simulation tick wasn't advancing automatically, causing:
- Time to remain at 0
- No physics calculations (velocity stayed 0, Mach stayed 0) 
- Missile never launching or moving
The issue stems from a fundamental difference in how Elodin handles simulation time in different modes:
- Elodin's runtime automatically manages `el.SimulationTick`
- The tick increments before each simulation step
- Time progresses naturally via the `set_time` system
- Everything becomes pure JAX functions
- `el.SimulationTick` is treated as regular state, not special
- The tick must be manually managed - it doesn't auto-increment
```python
@el.system
def set_time(
tick: el.Query[el.SimulationTick],
dt: …
```
> Add auto-tick advancement to JaxSim

- docs/public/content/reference/migration/to-0.15.md
docs(migration) for v0.15: fix typo world.schematics() → world.schematic()
> docs(migration): fix typo world.schematics() → world.schematic()

- Cargo.lock
- libs/elodin-editor/Cargo.toml
- libs/elodin-editor/src/ui/plot/mod.rs
- libs/elodin-editor/src/ui/plot/state.rs
- libs/elodin-editor/src/ui/plot/widget.rs
See this issue: https://github.com/elodin-sys/elodin/issues/139
- First lock activated
- The first plot-graph whose lock is toggled becomes the leader.
- No visible effect at first, but this plot will serve as the reference for `zoom_x`.
- Second lock (and subsequent ones)
- When another plot-graph is locked, it automatically synchronizes with the `zoom_x` of the already locked group.
- As a result, all locked plots share the same `zoom_x` state.
- Propagation of `zoom_x`
- Whenever a user applies a `zoom_x` (via the UI) on a locked plot, this zoom is transmitted to all other locked plots.
-This works in a peer-to-peer logic: each locked plot can temporarily become the “leader” while it’s being interacted with.
- On macOS: CMD + mouse wheel
This branch modifies `elodin-editor/Cargo.toml` …
> feat(plot): Enhanced plot zoom/pan interactions

- libs/db/eql/src/lib.rs
- libs/elodin-editor/src/lib.rs
- libs/elodin-editor/src/ui/command_palette/palette_items.rs
- libs/elodin-editor/src/ui/hierarchy.rs
This addresses issue #150: Sorts the components in the UI.
The change is simple. Instead of using a `HashMap` as a backing store for the EQL context, I switched it to a `BTreeMap`, which stores its keys in order. No extra allocations, no on-request sorting required.
I confirmed this by looking at the drones examples and doing a Command-P, "Create Graph", select "drone", and see that all its components are in alphabetical order.
```sh
cd lib/nox-py
cargo run --manifest-path=../../apps/elodin/Cargo.toml editor ../../examples/drone/main.py
```
> feature: Sort the components in UI.

- libs/nox/src/doctest.rs
- libs/nox/src/lib.rs
- libs/nox/src/noxpr/README.md
- libs/nox/src/noxpr/mod.rs
- libs/nox/src/noxpr/node.rs
`noxpr` is not publicly exposed. In `libs/nox/src/lib.rs`, it’s declared as a private module:
```rust
#[cfg(feature = "noxpr")]
mod noxpr; // not public (no `pub`)
```
- As a result, I could'nt include externally tested examples that would import `nox::noxpr` from another crate; it wouldn’t compile.
- Instead, I added snippets inspired by noxpr’s unit tests (from `noxpr/node.rs`). These are meant as small recipes to reuse from inside the nox crate (or its internal modules), not as standalone, executable examples.
> Initiate a README for noxpr

- CHANGELOG.md
- docs/public/content/releases/changelog.md
Updated the changelog post-hoc for the v0.15.0 release.
The changelog was not comprehensive when released. (Doh!) I updated it here, and I updated the [github release page](https://github.com/elodin-sys/elodin/releases/tag/v0.15.0) manually.
> doc: Update change log.

- libs/nox-ecs-macros/README.md
Create README for `nox-ecs-macros`; examples are included in improved `nox-ecs` README (https://github.com/elodin-sys/elodin/pull/176).
> Create README for nox-ecs-macros

- libs/elodin-editor/src/ui/command_palette/palette_items.rs
- libs/elodin-editor/src/ui/monitor.rs
- libs/elodin-editor/src/ui/schematic/load.rs
- libs/elodin-editor/src/ui/schematic/mod.rs
- libs/elodin-editor/src/ui/tiles.rs
- libs/impeller2/kdl/src/de.rs
- libs/impeller2/kdl/src/ser.rs
- libs/impeller2/wkt/src/gui.rs
This PR fixes issue #152. Instead of using the component ID directly, which are not human readable, this serializes the component name. This improves the human readable format and makes monitors that have been serialized work again.
This can be tested by running the following command :
```
cd libs/nox-py
. .venv/bin/activate; # See elodin/README if not present.
cargo run --manifest-path=../../apps/elodin/Cargo.toml editor examples/three-body.py
```
Hit Command-P "Create Monitor". Select a component. Observe monitor pane. Hit Command-P "Save Schematic As...", name it "a.kdl". 
Restart app. Hit Command-P "Load Schematic" a.kdl and observe monitor is present and working.
> Fix the component monitor KDL
